### ISSUE TITLE
Server authorization error: insufficient permissions

### ISSUE THREAD

**Issue by apedroheringer** [DavidMStraub/gramps-web-sync#18]
Hi, I'm trying to sync my Gramps on my desktop (Debian 12) with Gramps Web and I keep getting this error.
I'm using the default user created on gramps web installation
I tried creating a new user on owner groups, tried moved the gramps web from my pc (running on docker behind caddy + cloudflared) to a oracle vps (docker with caddy), disabled the orange proxy on cloudflare.com... Can someone help me?
Thank you!

**Comment by DavidMStraub** [comment]
Hi, I think this error message could also be triggered by wrong username and/or password.

**Comment by apedroheringer** [comment]
It's not wrong... I also tried to use the email instead of the username,
with no luck :/

Em qui., 10 de ago. de 2023 12:04, David Straub ***@***.***>
escreveu:

**Comment by DavidMStraub** [comment]
Do you have access to the server logs? If you enable debug logging you could check which endpoint triggers the 403 unauthorized.

**Comment by DavidMStraub** [comment]
Also, are you using the latest development version from here or the version in the official repository (installed via Gramps desktop)?

**Comment by apedroheringer** [comment]
Hi David, I'm using gramps 5.1.5 installed via the repository, and
grampsweb 5.1.5.

How can I access the logs? You mean the logs from "docker logs grampsweb"
or a file that I can access via "docker exec -it grampsweb bash"?
I tried searching how the access grampsweb logs but couldn't find
anything...

Em qui., 10 de ago. de 2023 15:03, David Straub ***@***.***>
escreveu:

**Comment by DavidMStraub** [comment]
Please go to settings -> system info and copy the version info.

> How can I access the logs? You mean the logs from "docker logs grampsweb"

Yes.

**Comment by apedroheringer** [comment]
> Please go to settings -> system info and copy the version info.

```
Gramps 5.1.5
Gramps Web API 1.1.10
Gramps.js 23.8.1
locale: en
multi-tree: false
task queue: true
```


> Do you have access to the server logs? If you enable debug logging you could check which endpoint triggers the 403 unauthorized.

```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
[2023-08-10 18:53:09 +0000] [11] [INFO] Starting gunicorn 21.2.0
[2023-08-10 18:53:09 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
[2023-08-10 18:53:09 +0000] [11] [INFO] Using worker: sync
[2023-08-10 18:53:09 +0000] [12] [INFO] Booting worker with pid: 12
[2023-08-10 18:53:09 +0000] [13] [INFO] Booting worker with pid: 13
[2023-08-10 18:53:09 +0000] [15] [INFO] Booting worker with pid: 15
[2023-08-10 18:53:09 +0000] [16] [INFO] Booting worker with pid: 16
[2023-08-10 18:53:09 +0000] [18] [INFO] Booting worker with pid: 18
[2023-08-10 18:53:09 +0000] [19] [INFO] Booting worker with pid: 19
[2023-08-10 18:53:10 +0000] [20] [INFO] Booting worker with pid: 20
[2023-08-10 18:53:10 +0000] [22] [INFO] Booting worker with pid: 22
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
```

When I login on https://myurl/login this error "Unable to init server: Could not connect: Connection refused" shows on log but it logins
When I try to login via gramps desktop I get the insufficient permissions error but nothing appears on the log


> My docker-compose

```
   grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    container_name: grampsweb
    restart: always
  #  ports:
  #    - "80:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "mytree"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GRAMPSWEB_BASE_URL: "https://myurl/"
      GRAMPSWEB_SECRET_KEY: "mykey"
    depends_on:
      - grampsweb_redis
    networks:
      - caddy_proxy
    volumes:
      - ${DOCKERDIR}/appdata/gramps/users:/app/users  # persist user database
      - ${DOCKERDIR}/appdata/gramps/index:/app/indexdir  # persist search index
      - ${DOCKERDIR}/appdata/gramps/thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - ${DOCKERDIR}/appdata/gramps/cache:/app/cache  # persist export and report caches
      - ${DOCKERDIR}/appdata/gramps/secret:/app/secret  # persist flask secret
      - ${DOCKERDIR}/appdata/gramps/db:/root/.gramps/grampsdb  # persist Gramps database
      - ${DOCKERDIR}/appdata/gramps/media:/app/media  # persist media files
      - ${DOCKERDIR}/appdata/gramps/tmp:/tmp

   grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    networks:
      - caddy_proxy

   grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: always
    networks:
      - caddy_proxy

```

Thank you for your help
